### PR TITLE
bump to 4.1

### PR DESCRIPTION
**Pull request by ericmjl**

### CODE REVIEW

**Comment by jakirkham** [comment]
Looks like this already happened, right? 😕

**Comment by ericmjl** [comment]
I had merge commit issues with the previous run. 4.2 also has the same problems. Being a git noob, I wasn't sure what to do, so I re-started from scratch.

**Comment by ericmjl** [comment]
By the way, @jakirkham, I'm wondering if there's the possibility of auto-emailing on passing all checks? It's kinda nice to have everything land in my inbox haha.

**Comment by jakirkham** [comment]
> I'm wondering if there's the possibility of auto-emailing on passing all checks?

Please raise that at the [conda-smithy issue tracker]( https://github.com/conda-forge/conda-smithy/issues ). Should be doable, but that would be the place to make this sort of change.

For me personally, that might be too noisy, but I suppose I can just configure my email to just archive them.

**Comment by jakirkham** [comment]
> I had merge commit issues with the previous run.

Hmm...looks ok to me.

> 4.2 also has the same problems. Being a git noob, I wasn't sure what to do, so I re-started from scratch. Sorry about that, @jakirkham 😞 .

Yeah, probably a rebase would do the trick. Normally I just do a bunch of these sequential on one branch, add branches for each release, and then rebase them from the bottom up. Though the last step is optional (I'm just very picky I guess).

**Pull request merged**
