### PR TITLE
Update to 4.0

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by ericmjl** [comment]
Thanks @jakirkham! Should we also do a 4.2 version?

**Comment by jakirkham** [comment]
Was going to build up to it. Does that sound reasonable?

**Comment by ericmjl** [comment]
yeah, definitely! are you going to handle it, or shall I? I'm happy to spend a bit of free time on it if you're busy. :smile:

**Comment by jakirkham** [comment]
Awesome, if you have time, go for it. I prepped the 4.0.x bumps in my fork if you just want to use those. Haven't gotten past that though. Sadly I forgot to drop the license comment in this PR so have added it in PR ( https://github.com/conda-forge/coverage-feedstock/pull/3 ).

**Pull request merged**
