### PR TITLE
bumped to version 4.1

### PR DESCRIPTION
**Pull request by ericmjl**

### CODE REVIEW

**Comment by jakirkham** [comment]
Sorry please fork.

**Comment by jakirkham** [comment]
It will auto release if it is a branch on the feedstock.

**Comment by ericmjl** [comment]
ohhhhh! got it. okay!

**Comment by jakirkham** [comment]
Sorry about that. I know it is not as clear as it should be.

**Comment by jakirkham** [comment]
Yeah, we've all done it at least once. Sometimes it happens by accident.

**Pull request closed without merging**
