### PR TITLE
Bump to 4.0.2

### PR DESCRIPTION
**Pull request by jakirkham**

### CODE REVIEW

**Comment by ericmjl** [comment]
cool stuff, i'll handle 4.1 and 4.2. I should **not** include the b`X` versions, right?

**Comment by jakirkham** [comment]
Meaning the betas? No point I think. First there are newer stable versions. Second we don't have an agreed upon pre-release system. See issue ( https://github.com/conda-forge/conda-forge.github.io/issues/147 ).

When doing 4.1.x and 4.2.x, please do the same thing that I have done. Make a PR for one release and then merge after it passes. This way we can ensure each release is built.

**Comment by jakirkham** [comment]
Thanks @ericmjl. 😄

**Comment by ericmjl** [comment]
@jakirkham git ot! :laugh:

**Comment by jakirkham** [comment]
Should add that I'm totally fine with self-merges on trivial releases (version and checksum update). If it gets funny, we should chat though.

**Comment by jakirkham** [comment]
It would also be great if we can keep these chronological. So 4.0.x bumps get merged first. Then 4.1.x and 4.2.x.

**Comment by ericmjl** [comment]
@jakirkham  no problem. I'll follow that order then.

**Comment by ericmjl** [comment]
btw, travis always seems to be the slowest amongst the three. is there a known reason why this is the case?

**Comment by jakirkham** [comment]
They are having some [issues]( https://www.traviscistatus.com/incidents/2p40l49r3yxd ) today. Though they seem to pertain to Linux VMs. Both Linux and Mac builds sit on the same build queue. So we may be backed up behind some Linux VMs from staged-recipes.

**Pull request merged**
